name: silasmiddleton
favicon: null
layout_spectrum: 0.245428376365453
typography_spectrum: 0.8343470995314419
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8778588310815394
  lightness: 0.24768794793635607
  saturation: 0.11354939872398973
  rhythmicContrast: 0.7973495593760163
purpose: []
